import type { SystemUser } from "./types";

// ─── Mock Data ────────────────────────────────────────────────────────────────

export const mockUsers: SystemUser[] = [
  {
    id: 1,
    name: "Engr. Ricardo Villanueva",
    title: "Provincial Engineer",
    role: "Admin",
    email: "r.villanueva@peo.gov.ph",
    contact: "+63 917 123 4567",
    status: "Active",
  },
  {
    id: 2,
    name: "Maria Santos",
    title: "Administrative Officer IV",
    role: "Super Admin",
    email: "m.santos@peo.gov.ph",
    contact: "+63 918 234 5678",
    status: "Active",
  },
  {
    id: 3,
    name: "Engr. Juan dela Cruz",
    title: "Highway Division Head",
    role: "Admin",
    email: "j.delacruz@peo.gov.ph",
    contact: "+63 919 345 6789",
    status: "Active",
  },
  {
    id: 4,
    name: "Ana Reyes",
    title: "Records Officer I",
    role: "Receiver",
    email: "a.reyes@peo.gov.ph",
    contact: "+63 920 456 7890",
    status: "Active",
  },
  {
    id: 5,
    name: "Engr. Carlos Mendoza",
    title: "Bridge Division Head",
    role: "Admin",
    email: "c.mendoza@peo.gov.ph",
    contact: "+63 921 567 8901",
    status: "Disabled",
  },
  {
    id: 6,
    name: "Liza Torres",
    title: "Administrative Aide VI",
    role: "Receiver",
    email: "l.torres@peo.gov.ph",
    contact: "+63 922 678 9012",
    status: "Active",
  },
  {
    id: 7,
    name: "Engr. Ramon Garcia",
    title: "Planning Division Head",
    role: "Admin",
    email: "r.garcia@peo.gov.ph",
    contact: "+63 923 789 0123",
    status: "Active",
  },
  {
    id: 8,
    name: "Engr. Paolo Tan",
    title: "Equipment Division Head",
    role: "Division",
    email: "p.tan@peo.gov.ph",
    contact: "+63 924 890 1234",
    status: "Active",
  },
];
